CREATE TABLE [dbo].[PLANO] (
    [PLANO_ID]              INT          NOT NULL,
    [PLANO_DESCR]           VARCHAR (50) NOT NULL,
    [PLANO_MINUTOS]         DECIMAL (18) DEFAULT ((0)) NOT NULL,
    [PLANO_PRECO]           DECIMAL (18) DEFAULT ((0)) NOT NULL,
    [PLANO_TARIFAEXCEDENTE] DECIMAL (18) DEFAULT ((0)) NOT NULL,
    [PLANO_ATIVO] BIT NOT NULL, 
    PRIMARY KEY CLUSTERED ([PLANO_ID] ASC)
);

