CREATE TABLE [dbo].[PRECO] (
    [PRECO_ID]          INT          IDENTITY (1, 1) NOT NULL,
    [PRECO_IDORIGEM]    INT          NOT NULL,
    [PRECO_IDDESTINO]   INT          NOT NULL,
    [PRECO_VALORMINUTO] DECIMAL (18) DEFAULT ((0)) NOT NULL,
    [PRECO_ATIVO] BIT NOT NULL, 
    PRIMARY KEY CLUSTERED ([PRECO_ID] ASC),
    CONSTRAINT [PRECO_FK1] FOREIGN KEY ([PRECO_IDORIGEM]) REFERENCES [dbo].[DDD] ([DDD_ID]),
    CONSTRAINT [PRECO_FK2] FOREIGN KEY ([PRECO_IDDESTINO]) REFERENCES [dbo].[DDD] ([DDD_ID])
);

