//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaleMais.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ADMIN
    {
        [ScaffoldColumn(false)]
        [Key]        
        [Display(Name="Id")]
        public int ADMIN_ID { get; set; }
        [Display(Name="Login")]
        [MaxLength(50)]
        [Required]
        public string ADMIN_LOGIN { get; set; }
        [Display(Name="Senha")]
        [MaxLength(20)]
        public string ADMIN_PASS { get; set; }
        [Display(Name="Ativo")]
        public bool ADMIN_ATIVO { get; set; }
    }
}
