//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaleMais.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DDD
    {
        public DDD()
        {
            this.PRECO = new HashSet<PRECO>();
            this.PRECO1 = new HashSet<PRECO>();
        }
        [ScaffoldColumn(false)]
        [Key]        
        [Display(Name="Id")]
        public int DDD_ID { get; set; }
        
        [Display(Name="Código")]
        [Required]
        public int DDD_CODIGO { get; set; }
        
        [Display(Name="Ativo")]
        public bool DDD_ATIVO { get; set; }
    
        public virtual ICollection<PRECO> PRECO { get; set; }
        public virtual ICollection<PRECO> PRECO1 { get; set; }
    }
}
