//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaleMais.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PLANO
    {
        [ScaffoldColumn(false)]
        [Key]        
        [Display(Name="Id")]
        public int PLANO_ID { get; set; }
        
        [Display(Name="Descrição")]
        [Required]
        public string PLANO_DESCR { get; set; }
        
        [Display(Name="Minutos")]
        [Required]
        public decimal PLANO_MINUTOS { get; set; }
        
        [Display(Name="Preço")]
        [Required]
        public decimal PLANO_PRECO { get; set; }
        
        [Display(Name="Tarifa Excedente")]
        [Required]
        public decimal PLANO_TARIFAEXCEDENTE { get; set; }
        
        [Display(Name="Ativo")]
        public bool PLANO_ATIVO { get; set; }
    }
}
