//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaleMais.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PRECO
    {
        
        [ScaffoldColumn(false)]
        [Key]        
        [Display(Name="Id")]
        public int PRECO_ID { get; set; }
        
        [Display(Name="DDD Origem")]
        [Required]
        public int PRECO_IDORIGEM { get; set; }
        
        [Display(Name="DDD Destino")]
        [Required]
        public int PRECO_IDDESTINO { get; set; }
        
        [Display(Name="Valor por Minuto")]
        [Required]
        public decimal PRECO_VALORMINUTO { get; set; }
        
        [Display(Name="Ativo")]
        public bool PRECO_ATIVO { get; set; }
    
        [Display(Name="DDD Origem")]
        public virtual DDD DDD { get; set; }
        
        [Display(Name="DDD Destino")]
        public virtual DDD DDD1 { get; set; }
    }
}
